services:
  - type: web
    name: himawari-qr
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: false

  - type: web
    name: himawari-qr-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    pullRequestPreviewsEnabled: false
